$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: hf-hubert-v1
endpoint_name: hf-hubert2-endpoint-sti

model: azureml:hubert-cpu:2
environment: azureml:hubert-env:2

instance_type: Standard_F2s_v2
instance_count: 1

request_settings:
  request_timeout_ms: 60000

code_configuration:
  code: hubert-model/model
  scoring_script: score.py
